# for all the voters from pdf

SELECT
  v.*
FROM
  voters AS v
  JOIN sections AS s ON v.section_id = s.id
WHERE
  s.pdf_id = 8;


#

2025-08-01 10:58:27,417 - INFO - Job 4e8ca2cd-9606-465b-b303-018b7a22cd38 status: processing - Saving extracted data for 2025-EROLLGEN-S06-141-FinalRoll-Revision2-GUJ-6-WI.pdf...
2025-08-01 10:58:27,418 - ERROR - Job 4e8ca2cd-9606-465b-b303-018b7a22cd38: Error in background task
Traceback (most recent call last):
  File "D:\python\voterapp\webapp.py", line 59, in background_task_runner
    loop.run_until_complete(
  File "C:\Users\Vansh\anaconda3\envs\voter-app\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\python\voterapp\pipeline_processor.py", line 475, in process_single_pdf_and_store_data_async
    pdf_id = insert_pdf_data(db_connection, {'header_metadata': header_data, 'footer_summary': footer_data}, pdf_file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\voterapp\pipeline_processor.py", line 328, in insert_pdf_data
    total_voters = footer.get("summary_voters_section_A", {}).get("rows", [{}])[-1].get("total_count")
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^
IndexError: list index out of range
2025-08-01 10:58:27,426 - INFO - Job 4e8ca2cd-9606-465b-b303-018b7a22cd38 status: error - An error occurred: list index out of range

